import assert from "node:assert/strict";
import { calculateOrderCharges, calculateOrderNotional, calculateTotalCashImpact, validateOrder } from "./orders.js";
import { applyCorporateActionToPosition, applyExecutionToPosition, calculateIncomeEvent, calculatePositionReport } from "./stockbroking.js";
import { applyBuyToPosition, applySellToPosition, calculateUnrealisedPnl, valuePosition } from "./portfolio.js";
import { calculateRiskScore, checkConcentrationLimit, hasSufficientCash } from "./risk.js";
import { applyRightsIssue, applyStockSplit, calculateDividendPayment } from "./corporateActions.js";
import { calculateCommission, calculateFxFee, calculateStampDuty } from "./fees.js";
import { applyPriceMovement, calculateMarketValue, calculateWeightedAveragePrice } from "./pricing.js";
import { calculateSettlementCashAmount, calculateSettlementDate, isSettlementDue } from "./settlement.js";

assert.strictEqual(calculateTotalCashImpact({"id":"id-1","side":"BUY","type":"STANDARD","status":"ACTIVE","symbol":"ABC","ticker":"ABC","quantity":10,"limitPrice":10,"price":10,"amount":100,"market":"UK","exchange":"LSE","country":"UK","currency":"GBP","settlementCurrency":"GBP","instrumentCurrency":"GBP"}, 10, 10), -103.5);
assert.deepStrictEqual(applyExecutionToPosition({"id":"id-1","symbol":"ABC","ticker":"ABC","quantity":10,"averagePrice":10,"price":10,"value":100,"marketValue":100,"currency":"GBP"}, {"id":"id-1","side":"BUY","type":"STANDARD","status":"ACTIVE","symbol":"ABC","ticker":"ABC","quantity":10,"limitPrice":10,"price":10,"amount":100,"market":"UK","exchange":"LSE","country":"UK","currency":"GBP","settlementCurrency":"GBP","instrumentCurrency":"GBP"}, 10), {"symbol":"ABC","quantity":20,"averagePrice":10});
assert.deepStrictEqual(calculatePositionReport({"id":"id-1","symbol":"ABC","ticker":"ABC","quantity":10,"averagePrice":10,"price":10,"value":100,"marketValue":100,"currency":"GBP"}, 10), {"symbol":"ABC","quantity":10,"averagePrice":10,"marketPrice":10,"marketValue":100,"unrealisedPnl":0,"pnlPercent":0});
assert.deepStrictEqual(applyCorporateActionToPosition({"id":"id-1","symbol":"ABC","ticker":"ABC","quantity":10,"averagePrice":10,"price":10,"value":100,"marketValue":100,"currency":"GBP"}, {"type":"STOCK_SPLIT","numerator":10,"denominator":10,"rightsRatio":10,"subscriptionPrice":10}), {"symbol":"ABC","quantity":10,"averagePrice":10});
assert.deepStrictEqual(applyBuyToPosition({"id":"id-1","symbol":"ABC","ticker":"ABC","quantity":10,"averagePrice":10,"price":10,"value":100,"marketValue":100,"currency":"GBP"}, 10, 100), {"symbol":"ABC","quantity":20,"averagePrice":55});
assert.deepStrictEqual(applySellToPosition({"id":"id-1","symbol":"ABC","ticker":"ABC","quantity":10,"averagePrice":10,"price":10,"value":100,"marketValue":100,"currency":"GBP"}, 10), {"symbol":"ABC","quantity":0,"averagePrice":10});
assert.throws(() => checkConcentrationLimit(-1, 10, 10), { message: "Values cannot be negative" });
assert.throws(() => calculateRiskScore(-1, 10, 10), { message: "Risk inputs cannot be negative" });
assert.strictEqual(validateOrder({"id":"id-1","side":"BUY","type":"STANDARD","status":"ACTIVE","symbol":"ABC","ticker":"ABC","quantity":10,"limitPrice":10,"price":10,"amount":100,"market":"UK","exchange":"LSE","country":"UK","currency":"GBP","settlementCurrency":"GBP","instrumentCurrency":"GBP"}), true);
assert.strictEqual(calculateOrderNotional({"id":"id-1","side":"BUY","type":"STANDARD","status":"ACTIVE","symbol":"ABC","ticker":"ABC","quantity":10,"limitPrice":10,"price":10,"amount":100,"market":"UK","exchange":"LSE","country":"UK","currency":"GBP","settlementCurrency":"GBP","instrumentCurrency":"GBP"}, 10), 100);
assert.strictEqual(calculateOrderCharges({"id":"id-1","side":"BUY","type":"STANDARD","status":"ACTIVE","symbol":"ABC","ticker":"ABC","quantity":10,"limitPrice":10,"price":10,"amount":100,"market":"UK","exchange":"LSE","country":"UK","currency":"GBP","settlementCurrency":10,"instrumentCurrency":10}, 10, 10), 3.5);
assert.strictEqual(valuePosition({"id":"id-1","symbol":"ABC","ticker":"ABC","quantity":10,"averagePrice":10,"price":10,"value":100,"marketValue":100,"currency":"GBP"}, 10), 100);
assert.strictEqual(calculateUnrealisedPnl({"id":"id-1","symbol":"ABC","ticker":"ABC","quantity":10,"averagePrice":10,"price":10,"value":100,"marketValue":100,"currency":"GBP"}, 10), 0);
assert.strictEqual(hasSufficientCash(10, {"id":"id-1","side":"BUY","type":"STANDARD","status":"ACTIVE","symbol":"ABC","ticker":"ABC","quantity":10,"limitPrice":10,"price":10,"amount":100,"market":"UK","exchange":"LSE","country":"UK","currency":"GBP","settlementCurrency":"GBP","instrumentCurrency":"GBP"}, 10, 10), false);
assert.strictEqual(checkConcentrationLimit(10, 10, 10), false);
assert.strictEqual(calculateRiskScore(10, 10, 10), 100);
assert.deepStrictEqual(applyStockSplit({"id":"id-1","symbol":"ABC","ticker":"ABC","quantity":10,"averagePrice":10,"price":10,"value":100,"marketValue":100,"currency":"GBP"}, 10, 10), {"symbol":"ABC","quantity":10,"averagePrice":10});
assert.deepStrictEqual(applyRightsIssue({"id":"id-1","symbol":"ABC","ticker":"ABC","quantity":10,"averagePrice":10,"price":10,"value":100,"marketValue":100,"currency":"GBP"}, 10, 10), {"symbol":"ABC","quantity":110,"averagePrice":10});
assert.strictEqual(calculateCommission(10, 10), 3);
assert.strictEqual(calculateStampDuty(10, "BUY", "UK"), 0.05);
assert.strictEqual(calculateFxFee(10, 10, 10), 0);
assert.strictEqual(calculateMarketValue(10, 100), 1000);
assert.strictEqual(applyPriceMovement(100, 10), 110);
assert.strictEqual(calculateWeightedAveragePrice(10, 10, 10, 10), 10);
assert.strictEqual(calculateSettlementDate(10, "UK"), 12);
assert.strictEqual(isSettlementDue(10, 10), true);
assert.throws(() => applyCorporateActionToPosition({"id":"id-1","symbol":"ABC","ticker":"ABC","quantity":10,"averagePrice":10,"price":10,"value":100,"marketValue":100,"currency":"GBP"}, null), { message: "Corporate action is required" });
assert.throws(() => calculateIncomeEvent({"id":"id-1","symbol":"ABC","ticker":"ABC","quantity":10,"averagePrice":10,"price":10,"value":100,"marketValue":100,"currency":"GBP"}, null), { message: "Income event is required" });
assert.throws(() => validateOrder({"id":"id-1","side":"BUY","type":"STANDARD","status":"ACTIVE","symbol":"ABC","ticker":"ABC","quantity":0,"limitPrice":10,"price":10,"amount":100,"market":"UK","exchange":"LSE","country":"UK","currency":"GBP","settlementCurrency":"GBP","instrumentCurrency":"GBP"}), { message: "Quantity must be positive" });
assert.throws(() => validateOrder({"id":"id-1","side":"BUY","type":"STANDARD","status":"ACTIVE","symbol":"ABC","ticker":"ABC","quantity":10,"limitPrice":-1,"price":10,"amount":100,"market":"UK","exchange":"LSE","country":"UK","currency":"GBP","settlementCurrency":"GBP","instrumentCurrency":"GBP"}), { message: "Limit price cannot be negative" });
assert.throws(() => applyBuyToPosition(null, 10, 100), { message: "Position is required" });
assert.throws(() => applySellToPosition(null, 10), { message: "Position is required" });
assert.throws(() => applySellToPosition({"id":"id-1","symbol":"ABC","ticker":"ABC","quantity":10,"averagePrice":10,"price":10,"value":100,"marketValue":100,"currency":"GBP"}, 0), { message: "Sell quantity must be positive" });
assert.throws(() => applySellToPosition({"id":"id-1","symbol":"ABC","ticker":"ABC","quantity":-1,"averagePrice":10,"price":10,"value":100,"marketValue":100,"currency":"GBP"}, 10), { message: "Cannot sell more than current holding" });
assert.throws(() => hasSufficientCash(-1, {"id":"id-1","side":"BUY","type":"STANDARD","status":"ACTIVE","symbol":"ABC","ticker":"ABC","quantity":10,"limitPrice":10,"price":10,"amount":100,"market":"UK","exchange":"LSE","country":"UK","currency":"GBP","settlementCurrency":"GBP","instrumentCurrency":"GBP"}, 10, 10), { message: "Cash balance cannot be negative" });
assert.throws(() => checkConcentrationLimit(10, 10, 101), { message: "Invalid concentration limit" });
assert.throws(() => applyStockSplit({"id":"id-1","symbol":"ABC","ticker":"ABC","quantity":10,"averagePrice":10,"price":10,"value":100,"marketValue":100,"currency":"GBP"}, 0, 10), { message: "Split ratio must be positive" });
assert.throws(() => calculateDividendPayment({"id":"id-1","symbol":"ABC","ticker":"ABC","quantity":10,"averagePrice":10,"price":10,"value":100,"marketValue":100,"currency":"GBP"}, -1, 10), { message: "Dividend cannot be negative" });
assert.throws(() => calculateDividendPayment({"id":"id-1","symbol":"ABC","ticker":"ABC","quantity":10,"averagePrice":10,"price":10,"value":100,"marketValue":100,"currency":"GBP"}, 10, 2), { message: "Invalid withholding tax rate" });
assert.throws(() => applyRightsIssue({"id":"id-1","symbol":"ABC","ticker":"ABC","quantity":10,"averagePrice":10,"price":10,"value":100,"marketValue":100,"currency":"GBP"}, -1, 10), { message: "Rights issue inputs cannot be negative" });
assert.throws(() => calculateCommission(-1, 10), { message: "Trade value cannot be negative" });
assert.throws(() => calculateStampDuty(-1, "BUY", "UK"), { message: "Trade value cannot be negative" });
assert.throws(() => calculateFxFee(-1, 10, 10), { message: "Trade value cannot be negative" });
assert.throws(() => calculateMarketValue(0, 100), { message: "Quantity must be positive" });
assert.throws(() => calculateMarketValue(10, -1), { message: "Price cannot be negative" });
assert.throws(() => applyPriceMovement(-1, 10), { message: "Price cannot be negative" });
assert.throws(() => calculateWeightedAveragePrice(-1, 10, 10, 10), { message: "Existing quantity cannot be negative" });
assert.throws(() => calculateWeightedAveragePrice(10, -1, 10, 10), { message: "Price cannot be negative" });
assert.throws(() => calculateWeightedAveragePrice(10, 10, 0, 10), { message: "Trade quantity must be positive" });
assert.throws(() => calculateSettlementDate(-1, "UK"), { message: "Trade day index cannot be negative" });
assert.throws(() => isSettlementDue(-1, 10), { message: "Day index cannot be negative" });
assert.throws(() => calculateSettlementCashAmount({"id":"id-1","side":"BUY","type":"STANDARD","status":"ACTIVE","symbol":"ABC","ticker":"ABC","quantity":10,"limitPrice":10,"price":10,"amount":100,"market":"UK","exchange":"LSE","country":"UK","currency":"GBP","settlementCurrency":"GBP","instrumentCurrency":"GBP"}, -1, [{"quantity":10,"side":"BUY"}]), { message: "Amount cannot be negative" });
assert.throws(() => validateOrder(null), { message: "Order is required" });
assert.throws(() => validateOrder({"id":"id-1","side":"BUY","type":"STANDARD","status":"ACTIVE","symbol":null,"ticker":"ABC","quantity":10,"limitPrice":10,"price":10,"amount":100,"market":"UK","exchange":"LSE","country":"UK","currency":"GBP","settlementCurrency":"GBP","instrumentCurrency":"GBP"}), { message: "Symbol is required" });
assert.throws(() => valuePosition(null, 10), { message: "Position is required" });
assert.throws(() => calculateUnrealisedPnl(null, 10), { message: "Position is required" });
assert.throws(() => applyStockSplit(null, 10, 10), { message: "Position is required" });
assert.throws(() => calculateDividendPayment(null, 10, 10), { message: "Position is required" });
assert.throws(() => applyRightsIssue(null, 10, 10), { message: "Position is required" });
assert.throws(() => calculateFxFee(10, null, 10), { message: "Currency is required" });
assert.throws(() => applyPriceMovement(100, -101), { message: "Movement percent cannot reduce price below zero" });
assert.throws(() => calculateSettlementCashAmount(null, 10, [{"quantity":10,"side":"BUY"}]), { message: "Order is required" });
