import assert from "node:assert/strict";
import { applyCorporateActionToPosition, calculateIncomeEvent, calculatePositionReport } from "./stockbroking.js";
import { applyBuyToPosition, applySellToPosition, calculateUnrealisedPnl, valuePosition } from "./portfolio.js";
import { calculateRiskScore, checkConcentrationLimit, hasSufficientCash } from "./risk.js";
import { validateOrder } from "./orders.js";
import { applyRightsIssue, applyStockSplit, calculateDividendPayment } from "./corporateActions.js";
import { calculateCommission, calculateFxFee, calculateStampDuty } from "./fees.js";
import { applyPriceMovement, calculateMarketValue, calculateWeightedAveragePrice } from "./pricing.js";
import { calculateSettlementCashAmount, calculateSettlementDate, isSettlementDue } from "./settlement.js";

assert.deepStrictEqual(calculatePositionReport({"quantity":10,"averagePrice":10,"symbol":"ABC"}, 10), {"symbol":"ABC","quantity":10,"averagePrice":10,"marketPrice":10,"marketValue":100,"unrealisedPnl":0,"pnlPercent":0});
assert.deepStrictEqual(applyBuyToPosition({"quantity":10,"averagePrice":10,"symbol":"ABC"}, 10, 100), {"symbol":"ABC","quantity":20,"averagePrice":55});
assert.deepStrictEqual(applySellToPosition({"quantity":10,"symbol":"ABC","averagePrice":10}, 10), {"symbol":"ABC","quantity":0,"averagePrice":10});
assert.throws(() => checkConcentrationLimit(-1, 10, 10), { message: "Values cannot be negative" });
assert.throws(() => calculateRiskScore(-1, 10, 10), { message: "Risk inputs cannot be negative" });
assert.strictEqual(validateOrder({"side":"BUY","symbol":"ABC","quantity":10,"limitPrice":10}), true);
assert.strictEqual(valuePosition({"quantity":10}, 10), 100);
assert.strictEqual(calculateUnrealisedPnl({"quantity":10,"averagePrice":10}, 10), 0);
assert.deepStrictEqual(applyStockSplit({"symbol":"ABC","quantity":10,"averagePrice":10}, 10, 10), {"symbol":"ABC","quantity":10,"averagePrice":10});
assert.deepStrictEqual(applyRightsIssue({"quantity":10,"averagePrice":10,"symbol":"ABC"}, 10, 10), {"symbol":"ABC","quantity":110,"averagePrice":10});
assert.strictEqual(calculateFxFee(10, 10, 10), 0);
assert.strictEqual(calculateMarketValue(10, 100), 1000);
assert.strictEqual(applyPriceMovement(100, 10), 110);
assert.strictEqual(calculateWeightedAveragePrice(10, 10, 10, 10), 10);
assert.throws(() => applyCorporateActionToPosition(10, null), { message: "Corporate action is required" });
assert.throws(() => calculateIncomeEvent(10, null), { message: "Income event is required" });
assert.throws(() => validateOrder({"quantity":0,"side":"BUY","symbol":"ABC","limitPrice":10}), { message: "Quantity must be positive" });
assert.throws(() => validateOrder({"limitPrice":-1,"side":"BUY","symbol":"ABC","quantity":10}), { message: "Limit price cannot be negative" });
assert.throws(() => applyBuyToPosition(null, 10, 100), { message: "Position is required" });
assert.throws(() => applySellToPosition(null, 10), { message: "Position is required" });
assert.throws(() => applySellToPosition({"quantity":10,"symbol":"ABC","averagePrice":10}, 0), { message: "Sell quantity must be positive" });
assert.throws(() => applySellToPosition({"quantity":-1,"symbol":"ABC","averagePrice":10}, 10), { message: "Cannot sell more than current holding" });
assert.throws(() => hasSufficientCash(-1, 10, 10, 10), { message: "Cash balance cannot be negative" });
assert.throws(() => checkConcentrationLimit(10, 10, 101), { message: "Invalid concentration limit" });
assert.throws(() => applyStockSplit({"symbol":"ABC","quantity":10,"averagePrice":10}, 0, 10), { message: "Split ratio must be positive" });
assert.throws(() => calculateDividendPayment({"quantity":10}, -1, 10), { message: "Dividend cannot be negative" });
assert.throws(() => calculateDividendPayment({"quantity":10}, 10, 2), { message: "Invalid withholding tax rate" });
assert.throws(() => applyRightsIssue({"quantity":10,"averagePrice":10,"symbol":"ABC"}, -1, 10), { message: "Rights issue inputs cannot be negative" });
assert.throws(() => calculateCommission(-1, 10), { message: "Trade value cannot be negative" });
assert.throws(() => calculateStampDuty(-1, "BUY", "UK"), { message: "Trade value cannot be negative" });
assert.throws(() => calculateFxFee(-1, 10, 10), { message: "Trade value cannot be negative" });
assert.throws(() => calculateMarketValue(0, 100), { message: "Quantity must be positive" });
assert.throws(() => calculateMarketValue(10, -1), { message: "Price cannot be negative" });
assert.throws(() => applyPriceMovement(-1, 10), { message: "Price cannot be negative" });
assert.throws(() => calculateWeightedAveragePrice(-1, 10, 10, 10), { message: "Existing quantity cannot be negative" });
assert.throws(() => calculateWeightedAveragePrice(10, -1, 10, 10), { message: "Price cannot be negative" });
assert.throws(() => calculateWeightedAveragePrice(10, 10, 0, 10), { message: "Trade quantity must be positive" });
assert.throws(() => calculateSettlementDate(-1, "UK"), { message: "Trade day index cannot be negative" });
assert.throws(() => isSettlementDue(-1, 10), { message: "Day index cannot be negative" });
assert.throws(() => calculateSettlementCashAmount({"quantity":10,"side":"BUY"}, -1, [{"quantity":10,"side":"BUY"}]), { message: "Amount cannot be negative" });
assert.throws(() => validateOrder(null), { message: "Order is required" });
assert.throws(() => validateOrder({"symbol":null,"side":"BUY","quantity":10,"limitPrice":10}), { message: "Symbol is required" });
assert.throws(() => valuePosition(null, 10), { message: "Position is required" });
assert.throws(() => calculateUnrealisedPnl(null, 10), { message: "Position is required" });
assert.throws(() => applyStockSplit(null, 10, 10), { message: "Position is required" });
assert.throws(() => calculateDividendPayment(null, 10, 10), { message: "Position is required" });
assert.throws(() => applyRightsIssue(null, 10, 10), { message: "Position is required" });
assert.throws(() => calculateFxFee(10, null, 10), { message: "Currency is required" });
assert.throws(() => applyPriceMovement(100, -101), { message: "Movement percent cannot reduce price below zero" });
assert.throws(() => calculateSettlementCashAmount(null, 10, [{"quantity":10,"side":"BUY"}]), { message: "Order is required" });
